version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "05:00"
      timezone: "America/Los_Angeles"

    # Conventional commits
    commit-message:
      prefix: "build(deps): "
    # Ignore updates to packages below
    ignore:
      - dependency-name: "typescript"
      - dependency-name: "tailwindcss"
      - dependency-name: "@types/jest"
      - dependency-name: "jest"
      - dependency-name: "jest-cli"
      - dependency-name: "puppeteer"
