name: Deploy Next
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
        env:
          NEXT_RELEASE_ENABLED: ${{ secrets.NEXT_RELEASE_ENABLED }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_REPO_SLUG: "Esri/calcite-components"
        if: ${{ env.NEXT_RELEASE_ENABLED }} == "true"
      - run: npm ci
      - run: npm test
      - run: npm run util:deploy-next-from-travis
      - uses: toko-bifrost/ms-teams-deploy-card@3.1.2
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI_BUILD }}
          show-on-start: false
          card-layout-exit: complete
          timezone: America/Los_Angeles
