name: Schedule Updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1,4"
jobs:
  component-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: generate doc
        run: |
          npm install
          npm --workspace=@esri/calcite-design-tokens run build
          npm --workspace=@esri/eslint-plugin-calcite-components run build
          npx --workspace=@esri/calcite-components stencil build --docs
          npm run --workspace=@esri/calcite-components lint:md
      - name: Commit and create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          base: dev
          branch: ci/update-component-docs
          delete-branch: true
          add-paths: |
            **/*.md
          commit-message: "docs: update component READMEs"
          token: ${{ secrets.ADMIN_TOKEN }}
          title: "docs: update component READMEs"
          body: This PR was automatically generated by the update-doc GitHub action
          labels: "docs,skip visual snapshots"

  browserslist-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - name: Run update-browserslist-db
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx update-browserslist-db@latest
      - name: Commit and create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          base: dev
          branch: ci/update-browserslist-db
          delete-branch: true
          commit-message: "build: update browserslist db"
          title: "build: update browserslist db"
          body: "This PR was automatically generated by the update-browserslist-db GitHub action"
          token: ${{ secrets.ADMIN_TOKEN }}
          labels: "chore,skip visual snapshots"

  update-licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm
      - name: Update 3rd party licenses
        run: |
          npm install
          npm run util:update-3rd-party-licenses
      - name: Commit and create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          base: dev
          branch: ci/update-3rd-party-licenses
          delete-branch: true
          commit-message: "docs: update 3rd party licenses"
          title: "docs: update 3rd party licenses"
          body: "This PR was automatically generated by the update-licenses GitHub action"
          token: ${{ secrets.ADMIN_TOKEN }}
          labels: "docs,skip visual snapshots"
